inherit: "configs/common.yaml"

data:
  scale: 2
  batch_size: 12
  val_batch_size: 1

model:
  name: "edsr"
  params:
    num_feats: 64
    num_blocks: 16
    res_scale: 0.1

train:
  grad_accum_steps: 1

